name: Swagnation2024
version: '${project.version}'
main: de.flocrafter.swagnation2024.Swagnation2024
api-version: 1.20
authors: [ FloCrafter ]
description: Swagnation Plugin 2024
website: https://github.com/FloCrafter
commands:
  Test: